# An example of application-local.yml config
spring:
  mongodb:
    # Override this if you are running MongoDB locally without Docker
    # uri: mongodb://root:some_secret_password@localhost:27017/db
    uri: mongodb://root:some_secret_password@mongo:27017/db

auth:
  jwt:
    secret: "your-very-long-base64-encoded-secret-here"
    expiration-time: 15m
    issuer: EveryExpense
  refresh-token:
    expiration-time: 7d

gemini:
  api-key: "your-api-key"
  model: "gemini-3.5-flash"

