# An example of application-local.yml config

auth:
  jwt:
    secret: "your-very-long-base64-encoded-secret-here"
    expiration-time: 15m
    issuer: EveryExpense
  refresh-token:
    expiration-time: 7d